### ISSUE TITLE
Adjust the way locks are used

### ISSUE THREAD

**Issue by sblackler** [compose-net/compose#111]
Again as part of #104 - we use an object to lock a dictionary when we could just lock on the dictionary itself. Minor perf thing. [See here](https://github.com/compose-net/compose/pull/104/files#r47062971)

**Comment by sblackler** [comment]
Resolved

**Comment by smudge202** [comment]
Safe to close this once #104 is merged?

**Comment by sblackler** [comment]
I guess. Will leave open :+1:
