### ISSUE TITLE
Compose Family

### ISSUE THREAD

**Issue by smudge202** [compose-net/compose#113]
I think I've mentioned this to most the collabs one by one, but want to create this issue to allow open discussion.

The #104 work has removed the [`CommandLineApplication`](https://github.com/compose-net/compose/blob/dev/src/Compose/CommandLineApplication.cs), and I'm not planning to add it back. The reason being: the oldest outstanding issue in the Compose project, #7.

Essentially, I think the `CommandLineApplication` should probably provide some out the box features to push good practices. To do so would require more dependencies which don't belong in _Compose_ itself.

As prompted by the repo transfer to this `compose-net` organisation, the intent is to create additional repos and packages. `Compose.CommandLine` (or `Compose.Console`?) would be one such package. My company (Gilmond) will (unbeknown to them) be contributing to a WinForms application. Web requires little to no work. Windows Services is a nightmare and it would be great to blackbox that stuff again within another package.

I don't know exactly what repos we'll end up with, but I suspect along the lines of:

* `Compose.CommandLine`
* `Compose.WinForms`
* `Compose.Wpf`
* `Compose.WindowsService`

In addition to host types, it gives us a nice spot to add things (if we ever get round to them) like `Compose.Fallback`.

Thoughts?

**Comment by danielcirket** [comment]
Sounds good to me, :+1:

**Comment by sblackler** [comment]
Yep, lets do this. :+1:

**Comment by danielcirket** [comment]
Should this not be left open while in progress?

**Comment by smudge202** [comment]
104 is getting collapsed on stream shortly. ;)
