### ISSUE TITLE
CommandLine Application Commands

### ISSUE THREAD

**Issue by smudge202** [compose-net/compose#7]
We currently have a very basic implementation of the CommandLineApplication.  As with XRE PackageManager and similar projects, we should add in the ability to define additional command based executions, and some command line switch detection/parsing.

**Comment by smudge202** [comment]
I'm increasingly needing this, and MS have some excellent [CommandLineUtils](https://github.com/aspnet/dnx/tree/dev/src/Microsoft.Framework.CommandLineUtils.Sources) we can _borrow_ from. Moving this to next release.

**Comment by smudge202** [comment]
Going to push this one back, as there's enough to do to get Compose published alongside the beta5 release today.

**Comment by herecydev** [comment]
This will need to be moved to an additional package because it will have new dependencies.

**Comment by smudge202** [comment]
For consideration when looking at CommandLine parsers: https://github.com/gsscoder/commandline

**Comment by smudge202** [comment]
Haven't read this article, but might be helpful: http://jameschambers.com/2015/09/supporting-options-and-arguments-in-your-dnx-commands/

**Comment by sblackler** [comment]
That looks like that could be a winner

**Comment by sblackler** [comment]
Break this out into a new package?

**Comment by smudge202** [comment]
Funny you should mention it, I just created #113 to discuss it.

**Comment by smudge202** [comment]
Migrated to [here](https://github.com/compose-net/compose-commandline/issues/1).
