### ISSUE TITLE
Add README to NuGet Package

### ISSUE THREAD

**Issue by smudge202** [compose-net/compose#76]
We need the Compose readme to display when installing Compose. However, we do not want the file to become a part of / referenced by the project that installs Compose.

As per #71, this is not currently possible under the `project.json` system, but should be reviewed periodically.

**Comment by herecydev** [comment]
[Update](http://blog.nuget.org/20150729/Introducing-nuget-uwp.html): Delivering content is no longer possible. Still no word on displaying content.

**Comment by smudge202** [comment]
I'm not sure I want to do this any more. If people have gone as far as installing the package they probably have sufficient information and links to the repository for any additional info they require.
