### ISSUE TITLE
Update xunit

### ISSUE THREAD

**Issue by smudge202** [compose-net/compose#97]
xunit doesn't work with beta6 yet. Needs resolving so we can run the tests and confirm we're ready to publish 0.1.5! /grumble

**Comment by herecydev** [comment]
Ran locally okay, all tests working.

**Comment by smudge202** [comment]
Say whaaa. Not for me. What's your `dnvm list` looking like?

**Comment by smudge202** [comment]
I should mention, this was prompted by a silently failing build issue: https://ci.appveyor.com/project/Smudge202/compose

Notice the core build didn't run. We've had differences in behaviour between core and full CLR trip us up before so it's important we test both in my opinion. Current build script may explain better?

**Comment by herecydev** [comment]
Hmm, I was using xunit that certainly wasn't running beta6 so unsure how that was even operational. Also I have it on [good authority](http://blog.nuget.org/20150729/Introducing-nuget-uwp.html) that we might need full fat dnx.

**Comment by smudge202** [comment]
I believe this will be resolved by #104
